# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QMainWindow, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(935, 605)
        MainWindow.setMinimumSize(QSize(935, 605))
        MainWindow.setMaximumSize(QSize(935, 605))
        font = QFont()
        font.setFamilies([u"Hack"])
        font.setPointSize(18)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"./static/icons/favicon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.logo = QLabel(self.centralwidget)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(0, 0, 300, 90))
        self.logo.setAutoFillBackground(False)
        self.logo.setPixmap(QPixmap(u"./static/icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.path = QLabel(self.centralwidget)
        self.path.setObjectName(u"path")
        self.path.setGeometry(QRect(15, 130, 60, 30))
        font1 = QFont()
        font1.setFamilies([u"Hack"])
        font1.setPointSize(16)
        font1.setBold(False)
        font1.setItalic(True)
        self.path.setFont(font1)
        self.path_info = QLabel(self.centralwidget)
        self.path_info.setObjectName(u"path_info")
        self.path_info.setGeometry(QRect(85, 130, 200, 30))
        font2 = QFont()
        font2.setFamilies([u"Hack"])
        font2.setPointSize(16)
        self.path_info.setFont(font2)
        self.path_info.setLayoutDirection(Qt.LeftToRight)
        self.path_info.setFrameShape(QFrame.Box)
        self.path_info.setAlignment(Qt.AlignCenter)
        self.path_info.setMargin(0)
        self.record = QLabel(self.centralwidget)
        self.record.setObjectName(u"record")
        self.record.setGeometry(QRect(50, 200, 200, 200))
        self.record.setMinimumSize(QSize(200, 200))
        self.record.setMaximumSize(QSize(200, 200))
        self.record.setPixmap(QPixmap(u"./static/icons/record.png"))
        self.record.setScaledContents(True)
        self.record.setAlignment(Qt.AlignCenter)
        self.line = QLabel(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(290, 10, 30, 520))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setLineWidth(5)
        self.name = QLabel(self.centralwidget)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(330, 30, 100, 30))
        font3 = QFont()
        font3.setFamilies([u"Hack"])
        font3.setPointSize(18)
        font3.setBold(True)
        font3.setItalic(True)
        self.name.setFont(font3)
        self.name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.name_info = QLabel(self.centralwidget)
        self.name_info.setObjectName(u"name_info")
        self.name_info.setGeometry(QRect(430, 30, 150, 30))
        self.name_info.setFont(font2)
        self.name_info.setFrameShape(QFrame.Box)
        self.name_info.setAlignment(Qt.AlignCenter)
        self.text = QLabel(self.centralwidget)
        self.text.setObjectName(u"text")
        self.text.setGeometry(QRect(330, 185, 105, 30))
        self.text.setFont(font3)
        self.text.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.text_info = QTextEdit(self.centralwidget)
        self.text_info.setObjectName(u"text_info")
        self.text_info.setGeometry(QRect(445, 185, 450, 150))
        self.text_info.setFont(font2)
        self.text_info.setFrameShape(QFrame.Box)
        self.emotion = QLabel(self.centralwidget)
        self.emotion.setObjectName(u"emotion")
        self.emotion.setGeometry(QRect(330, 355, 105, 30))
        self.emotion.setFont(font3)
        self.emotion.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pleasure = QLabel(self.centralwidget)
        self.pleasure.setObjectName(u"pleasure")
        self.pleasure.setGeometry(QRect(330, 405, 80, 30))
        self.pleasure.setFont(font3)
        self.pleasure.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.action = QLabel(self.centralwidget)
        self.action.setObjectName(u"action")
        self.action.setGeometry(QRect(330, 455, 80, 30))
        self.action.setFont(font3)
        self.action.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.flag1 = QCheckBox(self.centralwidget)
        self.flag1.setObjectName(u"flag1")
        self.flag1.setGeometry(QRect(330, 85, 175, 30))
        self.flag1.setFont(font3)
        self.flag1.setLayoutDirection(Qt.RightToLeft)
        self.flag2 = QCheckBox(self.centralwidget)
        self.flag2.setObjectName(u"flag2")
        self.flag2.setGeometry(QRect(525, 85, 175, 30))
        self.flag2.setFont(font3)
        self.flag2.setLayoutDirection(Qt.RightToLeft)
        self.flag3 = QCheckBox(self.centralwidget)
        self.flag3.setObjectName(u"flag3")
        self.flag3.setGeometry(QRect(720, 85, 175, 30))
        self.flag3.setFont(font3)
        self.flag3.setLayoutDirection(Qt.RightToLeft)
        self.emotion_info = QComboBox(self.centralwidget)
        icon1 = QIcon()
        icon1.addFile(u"./static/icons/service.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emotion_info.addItem(icon1, "")
        self.emotion_info.addItem(icon1, "")
        icon2 = QIcon()
        icon2.addFile(u"./static/icons/user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emotion_info.addItem(icon2, "")
        self.emotion_info.addItem(icon2, "")
        self.emotion_info.addItem(icon2, "")
        self.emotion_info.setObjectName(u"emotion_info")
        self.emotion_info.setGeometry(QRect(445, 355, 150, 30))
        self.emotion_info.setFont(font2)
        self.pleasure_info = QSlider(self.centralwidget)
        self.pleasure_info.setObjectName(u"pleasure_info")
        self.pleasure_info.setGeometry(QRect(445, 410, 400, 20))
        self.pleasure_info.setMinimum(1)
        self.pleasure_info.setMaximum(5)
        self.pleasure_info.setPageStep(1)
        self.pleasure_info.setValue(3)
        self.pleasure_info.setSliderPosition(3)
        self.pleasure_info.setOrientation(Qt.Horizontal)
        self.pleasure_info.setTickPosition(QSlider.TicksBothSides)
        self.pleasure_show = QLabel(self.centralwidget)
        self.pleasure_show.setObjectName(u"pleasure_show")
        self.pleasure_show.setGeometry(QRect(860, 410, 50, 20))
        font4 = QFont()
        font4.setFamilies([u"Hack"])
        font4.setPointSize(14)
        self.pleasure_show.setFont(font4)
        self.pleasure_show.setFrameShape(QFrame.NoFrame)
        self.pleasure_show.setFrameShadow(QFrame.Plain)
        self.pleasure_show.setAlignment(Qt.AlignCenter)
        self.action_info = QSlider(self.centralwidget)
        self.action_info.setObjectName(u"action_info")
        self.action_info.setGeometry(QRect(445, 460, 400, 20))
        self.action_info.setMinimum(1)
        self.action_info.setMaximum(5)
        self.action_info.setPageStep(1)
        self.action_info.setValue(3)
        self.action_info.setOrientation(Qt.Horizontal)
        self.action_info.setTickPosition(QSlider.TicksBothSides)
        self.action_show = QLabel(self.centralwidget)
        self.action_show.setObjectName(u"action_show")
        self.action_show.setGeometry(QRect(860, 460, 50, 20))
        self.action_show.setFont(font4)
        self.action_show.setFrameShape(QFrame.NoFrame)
        self.action_show.setFrameShadow(QFrame.Plain)
        self.action_show.setAlignment(Qt.AlignCenter)
        self.submit = QPushButton(self.centralwidget)
        self.submit.setObjectName(u"submit")
        self.submit.setGeometry(QRect(595, 520, 100, 40))
        self.submit.setFont(font)
        self.t_bar = QProgressBar(self.centralwidget)
        self.t_bar.setObjectName(u"t_bar")
        self.t_bar.setGeometry(QRect(15, 420, 290, 20))
        self.t_bar.setValue(0)
        self.flag4 = QCheckBox(self.centralwidget)
        self.flag4.setObjectName(u"flag4")
        self.flag4.setGeometry(QRect(330, 135, 175, 30))
        self.flag4.setFont(font3)
        self.flag4.setLayoutDirection(Qt.RightToLeft)
        self.replay = QPushButton(self.centralwidget)
        self.replay.setObjectName(u"replay")
        self.replay.setGeometry(QRect(40, 460, 60, 60))
        icon3 = QIcon()
        icon3.addFile(u"./static/icons/replay.png", QSize(), QIcon.Normal, QIcon.Off)
        self.replay.setIcon(icon3)
        self.replay.setIconSize(QSize(60, 60))
        self.play = QPushButton(self.centralwidget)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QRect(200, 460, 60, 60))
        icon4 = QIcon()
        icon4.addFile(u"./static/icons/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.play.setIcon(icon4)
        self.play.setIconSize(QSize(60, 60))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.emotion_info.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ding-Tag", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.logo.setText("")
        self.path.setText(QCoreApplication.translate("MainWindow", u"Path", None))
        self.path_info.setText("")
        self.record.setText("")
        self.line.setText("")
        self.name.setText(QCoreApplication.translate("MainWindow", u"\u6807\u6ce8\u8005: ", None))
        self.name_info.setText("")
        self.text.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u6587\u672c", None))
        self.emotion.setText(QCoreApplication.translate("MainWindow", u"\u60c5\u611f\u5206\u7c7b", None))
        self.pleasure.setText(QCoreApplication.translate("MainWindow", u"\u6109\u60a6\u7ef4", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u6fc0\u6d3b\u7ef4", None))
        self.flag1.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u5608\u6742\u6a21\u7cca", None))
        self.flag2.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u97f3\u91cf\u5f02\u5e38", None))
        self.flag3.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u65f6\u957f\u8fc7\u77ed", None))
        self.emotion_info.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5ba2\u670d-\u9971\u6ee1", None))
        self.emotion_info.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5ba2\u670d-\u5e73\u6de1", None))
        self.emotion_info.setItemText(2, QCoreApplication.translate("MainWindow", u"\u7528\u6237-\u79ef\u6781", None))
        self.emotion_info.setItemText(3, QCoreApplication.translate("MainWindow", u"\u7528\u6237-\u65e5\u5e38", None))
        self.emotion_info.setItemText(4, QCoreApplication.translate("MainWindow", u"\u7528\u6237-\u6d88\u6781", None))

        self.pleasure_show.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action_show.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.submit.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u4ea4", None))
        self.flag4.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u5305\u542b\u591a\u4eba", None))
#if QT_CONFIG(tooltip)
        self.replay.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cd\u64ad", None))
#endif // QT_CONFIG(tooltip)
        self.replay.setText("")
#if QT_CONFIG(tooltip)
        self.play.setToolTip(QCoreApplication.translate("MainWindow", u"\u64ad\u653e/\u6682\u505c", None))
#endif // QT_CONFIG(tooltip)
        self.play.setText("")
    # retranslateUi

