# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QMainWindow, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1165, 833)
        MainWindow.setMinimumSize(QSize(1165, 833))
        MainWindow.setMaximumSize(QSize(1165, 833))
        font = QFont()
        font.setFamilies([u"Hack"])
        font.setPointSize(18)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"./static/icons/favicon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.logo = QLabel(self.centralwidget)
        self.logo.setObjectName(u"logo")
        self.logo.setGeometry(QRect(0, 0, 300, 90))
        self.logo.setAutoFillBackground(False)
        self.logo.setPixmap(QPixmap(u"./static/icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.path = QLabel(self.centralwidget)
        self.path.setObjectName(u"path")
        self.path.setGeometry(QRect(15, 130, 60, 30))
        font1 = QFont()
        font1.setFamilies([u"Microsoft YaHei UI"])
        font1.setPointSize(18)
        font1.setBold(False)
        font1.setItalic(False)
        self.path.setFont(font1)
        self.path_info = QLabel(self.centralwidget)
        self.path_info.setObjectName(u"path_info")
        self.path_info.setGeometry(QRect(85, 130, 200, 30))
        font2 = QFont()
        font2.setFamilies([u"Microsoft JhengHei UI"])
        font2.setPointSize(16)
        self.path_info.setFont(font2)
        self.path_info.setLayoutDirection(Qt.LeftToRight)
        self.path_info.setFrameShape(QFrame.Box)
        self.path_info.setAlignment(Qt.AlignCenter)
        self.path_info.setMargin(0)
        self.record = QLabel(self.centralwidget)
        self.record.setObjectName(u"record")
        self.record.setGeometry(QRect(50, 200, 200, 200))
        self.record.setMinimumSize(QSize(200, 200))
        self.record.setMaximumSize(QSize(200, 200))
        self.record.setPixmap(QPixmap(u"./static/icons/record.png"))
        self.record.setScaledContents(True)
        self.record.setAlignment(Qt.AlignCenter)
        self.name = QLabel(self.centralwidget)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(330, 30, 100, 30))
        self.name.setFont(font1)
        self.name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.name_info = QLabel(self.centralwidget)
        self.name_info.setObjectName(u"name_info")
        self.name_info.setGeometry(QRect(430, 30, 150, 30))
        self.name_info.setFont(font2)
        self.name_info.setFrameShape(QFrame.Box)
        self.name_info.setAlignment(Qt.AlignCenter)
        self.text = QLabel(self.centralwidget)
        self.text.setObjectName(u"text")
        self.text.setGeometry(QRect(325, 220, 100, 30))
        self.text.setFont(font1)
        self.text.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.text_info = QTextEdit(self.centralwidget)
        self.text_info.setObjectName(u"text_info")
        self.text_info.setGeometry(QRect(440, 220, 650, 90))
        font3 = QFont()
        font3.setFamilies([u"Microsoft YaHei UI"])
        font3.setPointSize(16)
        self.text_info.setFont(font3)
        self.text_info.setFrameShape(QFrame.Box)
        self.emotion = QLabel(self.centralwidget)
        self.emotion.setObjectName(u"emotion")
        self.emotion.setGeometry(QRect(10, 650, 105, 30))
        self.emotion.setFont(font1)
        self.emotion.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pleasure = QLabel(self.centralwidget)
        self.pleasure.setObjectName(u"pleasure")
        self.pleasure.setGeometry(QRect(325, 425, 80, 30))
        self.pleasure.setFont(font1)
        self.pleasure.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.action = QLabel(self.centralwidget)
        self.action.setObjectName(u"action")
        self.action.setGeometry(QRect(325, 675, 80, 30))
        self.action.setFont(font1)
        self.action.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.flag1 = QCheckBox(self.centralwidget)
        self.flag1.setObjectName(u"flag1")
        self.flag1.setGeometry(QRect(325, 125, 190, 30))
        font4 = QFont()
        font4.setFamilies([u"Microsoft YaHei UI"])
        font4.setPointSize(16)
        font4.setBold(False)
        font4.setItalic(False)
        self.flag1.setFont(font4)
        self.flag1.setLayoutDirection(Qt.RightToLeft)
        self.flag1.setAutoFillBackground(False)
        self.flag2 = QCheckBox(self.centralwidget)
        self.flag2.setObjectName(u"flag2")
        self.flag2.setGeometry(QRect(530, 125, 145, 30))
        self.flag2.setFont(font4)
        self.flag2.setLayoutDirection(Qt.RightToLeft)
        self.flag3 = QCheckBox(self.centralwidget)
        self.flag3.setObjectName(u"flag3")
        self.flag3.setGeometry(QRect(690, 125, 390, 30))
        self.flag3.setFont(font4)
        self.flag3.setLayoutDirection(Qt.RightToLeft)
        self.emotion_info = QComboBox(self.centralwidget)
        icon1 = QIcon()
        icon1.addFile(u"./static/icons/laugh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emotion_info.addItem(icon1, "")
        icon2 = QIcon()
        icon2.addFile(u"./static/icons/usual.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emotion_info.addItem(icon2, "")
        icon3 = QIcon()
        icon3.addFile(u"./static/icons/depressed.png", QSize(), QIcon.Normal, QIcon.Off)
        self.emotion_info.addItem(icon3, "")
        self.emotion_info.setObjectName(u"emotion_info")
        self.emotion_info.setGeometry(QRect(50, 690, 230, 30))
        self.emotion_info.setFont(font3)
        self.emotion_info.setToolTipDuration(-1)
        self.pleasure_info = QSlider(self.centralwidget)
        self.pleasure_info.setObjectName(u"pleasure_info")
        self.pleasure_info.setGeometry(QRect(440, 430, 480, 20))
        self.pleasure_info.setMinimum(1)
        self.pleasure_info.setMaximum(5)
        self.pleasure_info.setPageStep(1)
        self.pleasure_info.setValue(3)
        self.pleasure_info.setSliderPosition(3)
        self.pleasure_info.setOrientation(Qt.Horizontal)
        self.pleasure_info.setTickPosition(QSlider.TicksBothSides)
        self.pleasure_show = QLabel(self.centralwidget)
        self.pleasure_show.setObjectName(u"pleasure_show")
        self.pleasure_show.setGeometry(QRect(940, 425, 50, 30))
        font5 = QFont()
        font5.setFamilies([u"Microsoft YaHei UI"])
        font5.setPointSize(18)
        font5.setBold(True)
        self.pleasure_show.setFont(font5)
        self.pleasure_show.setFrameShape(QFrame.NoFrame)
        self.pleasure_show.setFrameShadow(QFrame.Plain)
        self.pleasure_show.setAlignment(Qt.AlignCenter)
        self.action_info = QSlider(self.centralwidget)
        self.action_info.setObjectName(u"action_info")
        self.action_info.setGeometry(QRect(440, 680, 480, 20))
        self.action_info.setMinimum(1)
        self.action_info.setMaximum(5)
        self.action_info.setPageStep(1)
        self.action_info.setValue(3)
        self.action_info.setOrientation(Qt.Horizontal)
        self.action_info.setTickPosition(QSlider.TicksBothSides)
        self.action_show = QLabel(self.centralwidget)
        self.action_show.setObjectName(u"action_show")
        self.action_show.setGeometry(QRect(940, 675, 50, 30))
        self.action_show.setFont(font5)
        self.action_show.setFrameShape(QFrame.NoFrame)
        self.action_show.setFrameShadow(QFrame.Plain)
        self.action_show.setAlignment(Qt.AlignCenter)
        self.submit = QPushButton(self.centralwidget)
        self.submit.setObjectName(u"submit")
        self.submit.setGeometry(QRect(1010, 740, 100, 40))
        self.submit.setFont(font)
        self.t_bar = QProgressBar(self.centralwidget)
        self.t_bar.setObjectName(u"t_bar")
        self.t_bar.setGeometry(QRect(15, 420, 290, 20))
        self.t_bar.setValue(0)
        self.flag4 = QCheckBox(self.centralwidget)
        self.flag4.setObjectName(u"flag4")
        self.flag4.setGeometry(QRect(325, 170, 190, 30))
        self.flag4.setFont(font4)
        self.flag4.setLayoutDirection(Qt.RightToLeft)
        self.replay = QPushButton(self.centralwidget)
        self.replay.setObjectName(u"replay")
        self.replay.setGeometry(QRect(40, 460, 60, 60))
        icon4 = QIcon()
        icon4.addFile(u"./static/icons/replay.png", QSize(), QIcon.Normal, QIcon.Off)
        self.replay.setIcon(icon4)
        self.replay.setIconSize(QSize(60, 60))
        self.play = QPushButton(self.centralwidget)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QRect(200, 460, 60, 60))
        icon5 = QIcon()
        icon5.addFile(u"./static/icons/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.play.setIcon(icon5)
        self.play.setIconSize(QSize(60, 60))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(300, 0, 20, 833))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 559, 310, 3))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.role = QLabel(self.centralwidget)
        self.role.setObjectName(u"role")
        self.role.setGeometry(QRect(15, 570, 60, 30))
        font6 = QFont()
        font6.setFamilies([u"Microsoft YaHei UI"])
        font6.setPointSize(18)
        self.role.setFont(font6)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(310, 75, 855, 3))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.abnormal = QLabel(self.centralwidget)
        self.abnormal.setObjectName(u"abnormal")
        self.abnormal.setGeometry(QRect(325, 80, 150, 30))
        self.abnormal.setFont(font6)
        self.flag5 = QCheckBox(self.centralwidget)
        self.flag5.setObjectName(u"flag5")
        self.flag5.setGeometry(QRect(530, 170, 145, 30))
        self.flag5.setFont(font4)
        self.flag5.setLayoutDirection(Qt.RightToLeft)
        self.flag7 = QCheckBox(self.centralwidget)
        self.flag7.setObjectName(u"flag7")
        self.flag7.setGeometry(QRect(810, 170, 105, 30))
        self.flag7.setFont(font4)
        self.flag7.setLayoutDirection(Qt.RightToLeft)
        self.flag8 = QCheckBox(self.centralwidget)
        self.flag8.setObjectName(u"flag8")
        self.flag8.setGeometry(QRect(930, 170, 105, 30))
        self.flag8.setFont(font4)
        self.flag8.setLayoutDirection(Qt.RightToLeft)
        self.flag9 = QCheckBox(self.centralwidget)
        self.flag9.setObjectName(u"flag9")
        self.flag9.setGeometry(QRect(1050, 170, 105, 30))
        self.flag9.setFont(font4)
        self.flag9.setLayoutDirection(Qt.RightToLeft)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(310, 210, 855, 3))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(390, 320, 100, 100))
        self.label.setPixmap(QPixmap(u"./static/icons/p1_sam.png"))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(510, 320, 100, 100))
        self.label_2.setPixmap(QPixmap(u"./static/icons/p2_sam.png"))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(630, 320, 100, 100))
        self.label_3.setPixmap(QPixmap(u"./static/icons/p3_sam.png"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(750, 320, 100, 100))
        self.label_4.setPixmap(QPixmap(u"./static/icons/p4_sam.png"))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(870, 320, 100, 100))
        self.label_5.setPixmap(QPixmap(u"./static/icons/p5_sam.png"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(390, 460, 100, 90))
        font7 = QFont()
        font7.setFamilies([u"Microsoft YaHei UI"])
        font7.setPointSize(13)
        self.label_6.setFont(font7)
        self.label_6.setStyleSheet(u"background-color: #FF0000;")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(510, 460, 100, 90))
        self.label_7.setFont(font7)
        self.label_7.setStyleSheet(u"background-color: #FFA500;")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(630, 460, 100, 90))
        self.label_8.setFont(font7)
        self.label_8.setStyleSheet(u"background-color: #FFFF00;")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(750, 460, 100, 90))
        self.label_9.setFont(font7)
        self.label_9.setStyleSheet(u"background-color: #00FF00;")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(870, 460, 100, 90))
        self.label_10.setFont(font7)
        self.label_10.setStyleSheet(u"background-color: #00FFFF;")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(390, 570, 100, 100))
        self.label_11.setPixmap(QPixmap(u"./static/icons/a1_sam.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(510, 570, 100, 100))
        self.label_12.setPixmap(QPixmap(u"./static/icons/a2_sam.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(630, 570, 100, 100))
        self.label_13.setPixmap(QPixmap(u"./static/icons/a3_sam.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(750, 570, 100, 100))
        self.label_14.setPixmap(QPixmap(u"./static/icons/a4_sam.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(870, 570, 100, 100))
        self.label_15.setPixmap(QPixmap(u"./static/icons/a5_sam.png"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(390, 710, 100, 90))
        self.label_16.setFont(font7)
        self.label_16.setStyleSheet(u"background-color: #E6FFE6;")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(510, 710, 100, 90))
        self.label_17.setFont(font7)
        self.label_17.setStyleSheet(u"background-color: #B3FFB3;")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(750, 710, 100, 90))
        self.label_19.setFont(font7)
        self.label_19.setStyleSheet(u"background-color: #4DFF4D;")
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(870, 710, 100, 90))
        self.label_20.setFont(font7)
        self.label_20.setStyleSheet(u"background-color: #1AFF1A;")
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(630, 710, 100, 90))
        self.label_18.setFont(font7)
        self.label_18.setStyleSheet(u"background-color: #80FF80;")
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(310, 558, 855, 5))
        self.label_21.setStyleSheet(u"background-color: black;")
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(310, 312, 855, 5))
        self.label_22.setStyleSheet(u"background-color: black;")
        self.role_info = QComboBox(self.centralwidget)
        icon6 = QIcon()
        icon6.addFile(u"./static/icons/service.png", QSize(), QIcon.Normal, QIcon.Off)
        self.role_info.addItem(icon6, "")
        icon7 = QIcon()
        icon7.addFile(u"./static/icons/user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.role_info.addItem(icon7, "")
        self.role_info.setObjectName(u"role_info")
        self.role_info.setGeometry(QRect(50, 610, 230, 30))
        self.role_info.setFont(font3)
        self.role_info.setToolTipDuration(-1)
        self.flag10 = QCheckBox(self.centralwidget)
        self.flag10.setObjectName(u"flag10")
        self.flag10.setGeometry(QRect(50, 730, 170, 30))
        self.flag10.setFont(font4)
        self.flag10.setLayoutDirection(Qt.RightToLeft)
        self.flag11 = QCheckBox(self.centralwidget)
        self.flag11.setObjectName(u"flag11")
        self.flag11.setGeometry(QRect(50, 770, 170, 30))
        self.flag11.setFont(font4)
        self.flag11.setLayoutDirection(Qt.RightToLeft)
        self.flag6 = QCheckBox(self.centralwidget)
        self.flag6.setObjectName(u"flag6")
        self.flag6.setGeometry(QRect(690, 170, 105, 30))
        self.flag6.setFont(font4)
        self.flag6.setLayoutDirection(Qt.RightToLeft)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.emotion_info.setCurrentIndex(-1)
        self.role_info.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ding-Tag", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.logo.setText("")
        self.path.setText(QCoreApplication.translate("MainWindow", u"Path", None))
        self.path_info.setText("")
        self.record.setText("")
        self.name.setText(QCoreApplication.translate("MainWindow", u"\u6807\u6ce8\u8005: ", None))
        self.name_info.setText("")
        self.text.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u6587\u672c", None))
        self.emotion.setText(QCoreApplication.translate("MainWindow", u"\u60c5\u611f\u5206\u7c7b", None))
        self.pleasure.setText(QCoreApplication.translate("MainWindow", u"\u6109\u60a6\u7ef4", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u6fc0\u6d3b\u7ef4", None))
        self.flag1.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u5185\u5bb9\u6ca1\u6709\u542c\u61c2", None))
        self.flag2.setText(QCoreApplication.translate("MainWindow", u"\u8bed\u97f3\u5185\u5bb9\u4e0d\u5168", None))
        self.flag3.setText(QCoreApplication.translate("MainWindow", u"\u5305\u542b\u654f\u611f\u4fe1\u606f(\u7535\u8bdd\u53f7\u7801/\u8f66\u724c/\u5bb6\u5ead\u4f4f\u5740)", None))
        self.emotion_info.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6b63\u5411\u60c5\u7eea-\u79ef\u6781\u9971\u6ee1", None))
        self.emotion_info.setItemText(1, QCoreApplication.translate("MainWindow", u"\u6b63\u5e38\u60c5\u7eea-\u5e73\u9759\u7a33\u5b9a", None))
        self.emotion_info.setItemText(2, QCoreApplication.translate("MainWindow", u"\u8d1f\u5411\u60c5\u7eea-\u6d88\u6781\u66b4\u8e81", None))

        self.pleasure_show.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.action_show.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.submit.setText(QCoreApplication.translate("MainWindow", u"\u63d0\u4ea4", None))
        self.flag4.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u9759\u97f3\u90e8\u5206\u8fc7\u957f", None))
#if QT_CONFIG(tooltip)
        self.replay.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cd\u64ad", None))
#endif // QT_CONFIG(tooltip)
        self.replay.setText("")
#if QT_CONFIG(tooltip)
        self.play.setToolTip(QCoreApplication.translate("MainWindow", u"\u64ad\u653e/\u6682\u505c", None))
#endif // QT_CONFIG(tooltip)
        self.play.setText("")
        self.role.setText(QCoreApplication.translate("MainWindow", u"\u89d2\u8272", None))
        self.abnormal.setText(QCoreApplication.translate("MainWindow", u"\u5f02\u5e38\u60c5\u51b5\u8bb0\u5f55", None))
        self.flag5.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891\u5168\u4e3a\u6742\u97f3", None))
        self.flag7.setText(QCoreApplication.translate("MainWindow", u"\u58f0\u97f3\u504f\u5c0f", None))
        self.flag8.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u957f\u504f\u77ed", None))
        self.flag9.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u957f\u504f\u957f", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u6124\u6012\u7684\n"
"\u8f7b\u8511\u7684\n"
"\u75db\u82e6\u7684\n"
"\u6fc0\u6012\u7684", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6c14\u7684\n"
"\u51b7\u6de1\u7684\n"
"\u70e6\u607c\u7684\n"
"\u6c14\u6124\u7684", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6027\u7684", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u610f\u7684\n"
"\u6e29\u548c\u7684\n"
"\u6ee1\u610f\u7684\n"
"\u5feb\u4e50\u7684", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\u611f\u5174\u8da3\u7684\n"
"\u53cb\u597d\u7684\n"
"\u9ad8\u5174\u7684\n"
"\u5174\u594b\u7684", None))
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u56f0\u5026\u7684\n"
"\u5e73\u9759\u7684\n"
"\u653e\u677e\u7684\n"
"\u62d8\u8c28\u7684", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u5fc3\u4e0d\u5728\u7109\u7684\n"
"\u8f7b\u677e\u7684\n"
"\u5e73\u9759\u7684\n"
"\u5ff8\u6029\u7684", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u610f\u7684\n"
"\u6709\u5174\u8da3\u7684\n"
"\u5f15\u4eba\u6ce8\u610f\u7684\n"
"\u5403\u60ca\u7684", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u6e05\u9192\u7684\n"
"\u5174\u594b\u7684\n"
"\u611f\u5174\u8da3\u7684\n"
"\u60ca\u8bb6\u7684", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6027\u7684", None))
        self.label_21.setText("")
        self.label_22.setText("")
        self.role_info.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5ba2\u670d\u4eba\u5458", None))
        self.role_info.setItemText(1, QCoreApplication.translate("MainWindow", u"\u81f4\u7535\u7528\u6237", None))

        self.flag10.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u670d\u5f00\u5934\u793c\u8c8c\u8bed", None))
        self.flag11.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u670d\u7ed3\u675f\u793c\u8c8c\u8bed", None))
        self.flag6.setText(QCoreApplication.translate("MainWindow", u"\u9996\u5c3e\u6742\u97f3", None))
    # retranslateUi

